CREATE TABLE ROLE
(
    ID   SERIAL PRIMARY KEY,
    NAME VARCHAR(32) NOT NULL UNIQUE
);

CREATE TABLE USERS
(
    ID       BIGSERIAL PRIMARY KEY,
    USERNAME VARCHAR(32) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255),
    EMAIL    VARCHAR(64) NOT NULL UNIQUE,
    ROLE_ID  INTEGER REFERENCES role (ID)
);